from __future__ import annotations

from typing import List

from api.schemas import (
    CustomParams,
    ExperienceLevel,
    GenerateRequest,
    GenerateResponse,
    GeneratedQuestion,
    PromptMode,
    QuestionDifficulty,
    Specialization,
)
from api.services.memory import get_memory_store
from src.pipeline.runner import run_pipeline


_LEVEL_TO_DIFFICULTY = {
    ExperienceLevel.junior: QuestionDifficulty.easy,
    ExperienceLevel.middle: QuestionDifficulty.medium,
    ExperienceLevel.senior: QuestionDifficulty.hard,
}


def _build_job_description(
    specialization: Specialization,
    experience_level: ExperienceLevel,
    custom: CustomParams | None,
) -> str:
    if custom and custom.job_description:
        return custom.job_description.strip()

    parts = [f"{specialization.value.replace('_', ' ')} {experience_level.value} role."]
    if custom:
        if custom.tech_stack:
            parts.append(f"Tech stack: {custom.tech_stack.strip()}")
        if custom.company_profile:
            parts.append(f"Company: {custom.company_profile.strip()}")
    return " ".join(parts)


def _resolve_cv_text(request: GenerateRequest) -> tuple[str, PromptMode]:
    used_mode = request.mode
    if not request.cv_session_id and request.mode in (PromptMode.cv, PromptMode.mixed):
        used_mode = PromptMode.specialization

    cv_text = ""
    if request.cv_session_id:
        stored = get_memory_store().get_cv(request.cv_session_id)
        if not stored:
            raise ValueError(f"Unknown cv_session_id: {request.cv_session_id}")
        cv_text = stored["text"]

    if used_mode == PromptMode.cv and not cv_text:
        raise ValueError("CV-focused mode requires an uploaded CV.")

    return cv_text, used_mode


def _result_to_question(result, difficulty: QuestionDifficulty, category: str) -> GeneratedQuestion:
    skill_names = [s.entity for s in result.skills]
    explanation = (
        f"Skills extracted: {', '.join(skill_names) or 'none'}. "
        "Generated by SA-AQG (NER + RAG + Gemini)."
    )
    return GeneratedQuestion(
        question=result.generated_question,
        ideal_answer=result.reference_answer,
        explanation=explanation,
        difficulty=difficulty,
        category=category,
    )


def generate_questions(request: GenerateRequest) -> GenerateResponse:
    cv_text, used_mode = _resolve_cv_text(request)
    job_description = _build_job_description(
        request.specialization,
        request.experience_level,
        request.custom,
    )
    difficulty = _LEVEL_TO_DIFFICULTY[request.experience_level]
    category = request.specialization.value
    num_questions = min(request.num_questions, 10)

    questions: List[GeneratedQuestion] = []
    for _ in range(num_questions):
        result = run_pipeline(
            cv_text=cv_text,
            job_description=job_description,
            run_shap=False,
            skip_evaluation=True,
        )
        questions.append(_result_to_question(result, difficulty, category))

    cv_summary = cv_text[:500] if cv_text else None
    return GenerateResponse(
        questions=questions,
        used_mode=used_mode,
        cv_summary=cv_summary,
    )
